version: '3'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6380:6379"
      - "8001:8001"  

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  
      MYSQL_DATABASE: Events
      MYSQL_PASSWORD: password
      MYSQL_USER : user
    

  go_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
    - ./logs:/logs